apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: container-name
          image: paulbouwer/hello-kubernetes:1.10
          env: 
          - name: MESSAGE
            value: "Hello from app two"
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: app-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: nginx
          image: paulbouwer/hello-kubernetes:1.10
          env: 
          - name: MESSAGE
            value: "Hello from app one"
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: app-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
        - name: nginx
          image: paulbouwer/hello-kubernetes:1.10
          env: 
          - name: MESSAGE
            value: "Hello from app three"
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: app-3