apiVersion: v1
kind: Service
metadata:
  name: serve-1
spec:
  selector:
    app: app-1
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serve-2
spec:
  selector:
    app: app-2
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serve-3
spec:
  selector:
    app: app-3
  ports:
    - port: 80
      targetPort: 8080